apiVersion: v1
kind: ConfigMap
metadata:
  name: pulse-config
  namespace: pulse
data:
  KAFKA_BROKERS: kafka:9092
  KAFKA_TOPIC: pulse.events
  KAFKA_GROUP: pulse-processor
  REDIS_ADDR: redis:6379
  QUERY_GRPC_ADDR: query:50051
  INGEST_URL: http://ingest:8080
