apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  namespace: pulse
  labels:
    app: ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: ingest
          image: pulse-ingest:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: pulse-config
            - secretRef:
                name: pulse-db
          env:
            - name: HTTP_ADDR
              value: ":8080"
            - name: GIN_MODE
              value: release
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ingest
  namespace: pulse
spec:
  selector:
    app: ingest
  ports:
    - name: http
      port: 8080
      targetPort: http
