// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Source     string `json:"source"`
	Payload    string `json:"payload"`
	OccurredAt string `json:"occurredAt"`
}

type Query struct {
}
